language: python
group: travis_latest

cache: pip

matrix:
    include:
    - name: "Linux Python 3.5"
      os: linux
      python: 3.5
      install: pip install ".[rekall]"

    - name: "Linux Python 3.6"
      os: linux
      python: 3.6
      install: pip install ".[rekall]"

    - name: "Linux Python 3.7"
      os: linux
      python: 3.7
      dist: xenial
      install: pip install .

    - name: "Windows Python 3.5"
      os: windows
      language: sh
      install: pip install ".[rekall]"
      before_install:
      - choco install python3 --version 3.5.4
      - export PATH="/c/Python35:/c/Python35/Scripts:$PATH"

    - name: "Windows Python 3.6"
      os: windows
      language: sh
      install: pip install .
      before_install:
        - choco install python3 --version 3.6.8
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"

    - name: "Windows Python 3.7"
      os: windows
      language: sh
      install: pip install .
      before_install:
          - choco install python3 --version 3.7.3
          - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"

    - name: "MacOSX Python 3.6"
      os: osx
      python: 3.6
      language: sh
      install: pip3 install -e ".[rekall]"

    - name: "MacOSX Python 3.7"
      os: osx
      python: 3.7
      language: sh
      install: pip3 install -e .

script: mkdir -p data && pytest
